export const CAR_MODELS: Record<string, string[]> = {
  "Alfa Romeo": ["Giulietta", "Giulia", "Stelvio", "Tonale", "Tonale Plug-in Hybrid", "Mito", "159", "147", "Brera", "Spider"],
  "Audi": ["A1", "A3", "A3 TFSI e (Ibrida)", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q3 TFSI e", "Q4 e-tron", "Q5", "Q5 TFSI e", "Q7", "Q8", "TT", "R8", "e-tron"],
  "BMW": ["Serie 1", "Serie 2", "Serie 2 Active Tourer PHEV", "Serie 3", "Serie 3 PHEV", "Serie 4", "Serie 5", "Serie 6", "Serie 7", "X1", "X1 xDrive25e", "X2", "X3", "X3 xDrive30e", "X4", "X5", "X5 xDrive50e", "X6", "X7", "Z4", "i3", "i4", "iX"],
  "Citroën": ["C1", "C3", "C3 Aircross", "C4", "C4 Cactus", "C5 Aircross", "C5 Aircross Hybrid", "C5 X", "C5 X Hybrid", "Berlingo", "Ami"],
  "Cupra": ["Formentor", "Formentor e-HYBRID", "Born", "Leon", "Leon e-HYBRID", "Ateca", "Tavascan"],
  "Dacia": ["Sandero", "Duster", "Jogger", "Jogger Hybrid", "Spring", "Logan", "Lodgy"],
  "DS Automobiles": ["DS 3", "DS 4", "DS 4 E-TENSE", "DS 7", "DS 7 E-TENSE", "DS 9"],
  "Ferrari": ["488", "812 Superfast", "Roma", "Portofino", "SF90", "SF90 Stradale (Ibrida)", "Purosangue", "F8 Tributo", "296 GTB", "296 GTB (Ibrida)"],
  "Fiat": ["500", "500 Hybrid", "500X", "500X Hybrid", "500L", "Panda", "Panda Hybrid", "Punto", "Tipo", "Tipo Hybrid", "Freemont", "Bravo", "Qubo", "Doblò", "Multipla"],
  "Ford": ["Fiesta", "Focus", "Puma", "Puma Hybrid", "Kuga", "Kuga PHEV", "Mondeo", "Mustang", "Mustang Mach-E", "EcoSport", "Explorer", "Explorer PHEV", "Bronco"],
  "Honda": ["Civic", "Civic e:HEV", "HR-V", "HR-V e:HEV", "CR-V", "CR-V e:HEV", "CR-V e:PHEV", "Jazz", "Jazz e:HEV", "ZR-V", "ZR-V e:HEV", "e"],
  "Hyundai": ["i10", "i20", "i30", "Tucson", "Tucson Hybrid", "Tucson PHEV", "Kona", "Kona Hybrid", "Santa Fe", "Santa Fe Hybrid", "Santa Fe PHEV", "Ioniq 5", "Ioniq 6", "Bayon"],
  "Jeep": ["Renegade", "Renegade 4xe", "Renegade e-Hybrid", "Compass", "Compass 4xe", "Compass e-Hybrid", "Cherokee", "Grand Cherokee", "Grand Cherokee 4xe", "Wrangler", "Wrangler 4xe", "Avenger", "Avenger e-Hybrid", "Gladiator"],
  "Kia": ["Picanto", "Rio", "Ceed", "Sportage", "Sportage Hybrid", "Sportage PHEV", "Stonic", "Niro", "Niro HEV", "Niro PHEV", "Sorento", "Sorento Hybrid", "Sorento PHEV", "EV6", "EV9"],
  "Lamborghini": ["Huracán", "Aventador", "Urus", "Revuelto", "Revuelto (Ibrida)", "Gallardo"],
  "Lancia": ["Ypsilon", "Ypsilon Hybrid", "Delta", "Musa", "Thema"],
  "Land Rover": ["Range Rover", "Range Rover PHEV", "Range Rover Sport", "Range Rover Sport PHEV", "Range Rover Evoque", "Range Rover Evoque PHEV", "Range Rover Velar", "Defender", "Defender PHEV", "Discovery", "Discovery Sport", "Discovery Sport PHEV"],
  "Lexus": ["LBX", "UX", "UX Hybrid", "NX", "NX Hybrid", "NX PHEV", "RX", "RX Hybrid", "RX PHEV", "ES", "ES Hybrid", "LS", "LS Hybrid", "LC", "LC Hybrid"],
  "Maserati": ["Ghibli", "Ghibli Hybrid", "Levante", "Levante Hybrid", "Quattroporte", "Grecale", "Grecale Folgore", "MC20", "GranTurismo"],
  "Mazda": ["Mazda2", "Mazda2 Hybrid", "Mazda3", "Mazda3 M Hybrid", "CX-30", "CX-30 M Hybrid", "CX-5", "CX-60", "CX-60 PHEV", "MX-5", "MX-30", "MX-30 R-EV"],
  "Mercedes-Benz": ["Classe A", "Classe A EQ Power", "Classe B", "Classe B EQ Power", "Classe C", "Classe C EQ Power", "Classe E", "Classe E EQ Power", "Classe S", "Classe G", "GLA", "GLA EQ Power", "GLB", "GLC", "GLC EQ Power", "GLE", "GLE EQ Power", "GLS", "CLA", "CLA EQ Power", "CLS", "EQA", "EQB", "EQC", "EQE", "EQS", "AMG GT"],
  "Mini": ["Cooper", "Cooper SE", "Countryman", "Countryman PHEV", "Clubman", "Aceman"],
  "Nissan": ["Qashqai", "Qashqai e-POWER", "Juke", "Juke Hybrid", "Micra", "Leaf", "X-Trail", "X-Trail e-POWER", "Ariya"],
  "Opel": ["Corsa", "Astra", "Astra Plug-in Hybrid", "Mokka", "Crossland", "Grandland", "Grandland Plug-in Hybrid", "Adam", "Insignia"],
  "Peugeot": ["208", "308", "308 Hybrid", "2008", "3008", "3008 Hybrid", "3008 Plug-in Hybrid", "5008", "5008 Hybrid", "508", "508 PSE (Ibrida)", "Partner", "Rifter"],
  "Porsche": ["911", "Cayenne", "Cayenne E-Hybrid", "Macan", "Panamera", "Panamera E-Hybrid", "Taycan", "718 Boxster", "718 Cayman"],
  "Renault": ["Clio", "Clio E-Tech Hybrid", "Captur", "Captur E-Tech Hybrid", "Megane", "Megane E-Tech PHEV", "Kadjar", "Twingo", "Zoe", "Scenic", "Kangoo", "Arkana", "Arkana E-Tech Hybrid", "Austral", "Austral E-Tech Hybrid", "Espace", "Espace E-Tech Hybrid"],
  "Seat": ["Ibiza", "Leon", "Leon e-HYBRID", "Arona", "Ateca", "Tarraco", "Tarraco e-HYBRID", "Mii"],
  "Skoda": ["Fabia", "Octavia", "Octavia iV (PHEV)", "Kamiq", "Karoq", "Kodiaq", "Kodiaq iV (PHEV)", "Enyaq", "Superb", "Superb iV (PHEV)", "Scala"],
  "Smart": ["Fortwo", "Forfour", "#1", "#3"],
  "Subaru": ["Impreza", "Impreza e-Boxer", "XV", "XV e-Boxer", "Forester", "Forester e-Boxer", "Outback", "BRZ", "Solterra"],
  "Suzuki": ["Swift", "Swift Hybrid", "Ignis", "Ignis Hybrid", "Vitara", "Vitara Hybrid", "Jimny", "S-Cross", "S-Cross Hybrid", "Swace", "Swace Hybrid", "Across", "Across Plug-in"],
  "Tesla": ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
  "Toyota": ["Yaris", "Yaris Hybrid", "Yaris Cross", "Yaris Cross Hybrid", "Corolla", "Corolla Hybrid", "RAV4", "RAV4 Hybrid", "RAV4 Plug-in Hybrid", "C-HR", "C-HR Hybrid", "Aygo", "Aygo X", "Prius", "Prius Plug-in Hybrid", "Land Cruiser", "Hilux", "Supra", "bZ4X"],
  "Volkswagen": ["Golf", "Golf eHybrid", "Golf GTE", "Polo", "Passat", "Passat eHybrid", "Tiguan", "Tiguan eHybrid", "T-Roc", "T-Cross", "Up!", "Touareg", "Touareg eHybrid", "ID.3", "ID.4", "ID.5", "ID.7", "Taigo", "Arteon", "Arteon eHybrid"],
  "Volvo": ["XC40", "XC40 Recharge", "XC60", "XC60 Recharge", "XC90", "XC90 Recharge", "V40", "V60", "V60 Recharge", "V90", "V90 Recharge", "S60", "S60 Recharge", "S90", "S90 Recharge", "EX30", "EX90", "C40"]
};
